"use client"
// import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/reused-components/Header";
import { Provider } from 'react-redux';
import { store } from '../redux/store'; 
import { Toaster } from "@/components/ui/sonner";
import { Toaster as Toast }  from "@/components/ui/toaster";
import {  Inter, JetBrains_Mono } from "next/font/google";
import OrganizationSetupModal from "@/components/reused-components/OrgSetupModal";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased bg-stone-200`}
      >
        <Provider store={store}>
        <Header />
        <OrganizationSetupModal />
        {children}
        <Toaster/>
        <Toast/>
        </Provider> 
      </body>
    </html>
  );
}
